### ISSUE TITLE
IFR computation typo in code

### ISSUE THREAD

**Issue by joemzhao** [mulab-mir/muchomusic#5]
Hi authors, thanks for the nice work!

It looks like the IFR is reported as accurrcy in the code:

https://github.com/mulab-mir/muchomusic/blob/b50494d30af80a088e568b3630a875d6427bf672/evaluate.py#L85

would it be '1.0 - scores["unanswered_rate"]', according to the paper "FR is given by the percentage of generated answers
that correspond to one of the given options." ?

it would be great if you could clearify -- thank you!

**Comment by ilaria-manco** [comment]
Thanks for spotting this @joemzhao! It should now be fixed 🙂
